name: test
run-name: ${{ github.actor }} is testing startle
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published
jobs:
  test:
    name: "Run tests"
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install hatch
          pip install .[test]
      - name: Run tests
        run: hatch run test:pytest
      - name: Build dist
        run: hatch build
      - name: Publish
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@release/v1
        environment: pypi
